Add required OTEL-dependency
Before this commit, attempting to load the namespace
open-telemetry.exporter-sender-jdk would result in an error:

   Caused by java.lang.NoClassDefFoundError
   io/grpc/ManagedChannel
   [...]